# This is a basic workflow to help you get started with Actions

name: Node js application

on:[push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: set up Node.js
        run: actions/setup-node@v2
        with:
          node-version: '14'

      - name: install dependencies
        run: npm install

      - name: Run tests
        run: npm test
